// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Warehouse.Api.src.Domain;

#nullable disable

namespace Warehouse.Api.Migrations
{
    [DbContext(typeof(BaseDbContext))]
    [Migration("20250706071041_initMig")]
    partial class initMig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Warehouse.Api.src.Domain.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.HasKey("Id");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("Warehouse.Api.src.Domain.Entities.Order", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer")
                        .HasColumnName("customer_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("ProductItems")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("product_items");

                    b.Property<byte>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("Warehouse.Api.src.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BlockNumber")
                        .HasColumnType("integer")
                        .HasColumnName("block_number");

                    b.Property<int>("ColorId")
                        .HasColumnType("integer")
                        .HasColumnName("color_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<int>("PieceNumber")
                        .HasColumnType("integer")
                        .HasColumnName("piece_number");

                    b.Property<float>("Price")
                        .HasColumnType("real")
                        .HasColumnName("price");

                    b.Property<int>("ProductModelId")
                        .HasColumnType("integer")
                        .HasColumnName("product_model_id");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("size");

                    b.Property<int>("Stock")
                        .HasColumnType("integer")
                        .HasColumnName("stock");

                    b.Property<string>("Thumbnail")
                        .HasColumnType("text")
                        .HasColumnName("thumbnail");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ColorId");

                    b.HasIndex("ProductModelId");

                    b.HasIndex("UserId");

                    b.ToTable("products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BlockNumber = 20,
                            ColorId = 2,
                            CreatedAt = new DateTime(2025, 7, 6, 7, 10, 41, 268, DateTimeKind.Utc).AddTicks(8723),
                            IsDeleted = false,
                            PieceNumber = 682,
                            Price = 9.07f,
                            ProductModelId = 1,
                            Size = "96",
                            Stock = 6,
                            Thumbnail = "https://loremflickr.com/320/240?lock=1758283157",
                            UpdatedAt = new DateTime(2025, 7, 6, 7, 10, 41, 268, DateTimeKind.Utc).AddTicks(8719),
                            UserId = new Guid("3ca4ae80-3af8-48f6-957d-ea00c5a0d3f9")
                        },
                        new
                        {
                            Id = 2,
                            BlockNumber = 19,
                            ColorId = 1,
                            CreatedAt = new DateTime(2025, 7, 6, 7, 10, 41, 273, DateTimeKind.Utc).AddTicks(8947),
                            IsDeleted = false,
                            PieceNumber = 290,
                            Price = 9.36f,
                            ProductModelId = 1,
                            Size = "96",
                            Stock = 34,
                            Thumbnail = "https://loremflickr.com/320/240?lock=1707134601",
                            UpdatedAt = new DateTime(2025, 7, 6, 7, 10, 41, 273, DateTimeKind.Utc).AddTicks(8944),
                            UserId = new Guid("3ca4ae80-3af8-48f6-957d-ea00c5a0d3f9")
                        },
                        new
                        {
                            Id = 3,
                            BlockNumber = 4,
                            ColorId = 2,
                            CreatedAt = new DateTime(2025, 7, 6, 7, 10, 41, 273, DateTimeKind.Utc).AddTicks(9215),
                            IsDeleted = false,
                            PieceNumber = 302,
                            Price = 10.64f,
                            ProductModelId = 2,
                            Size = "160",
                            Stock = 29,
                            Thumbnail = "https://loremflickr.com/320/240?lock=869076132",
                            UpdatedAt = new DateTime(2025, 7, 6, 7, 10, 41, 273, DateTimeKind.Utc).AddTicks(9215),
                            UserId = new Guid("3ca4ae80-3af8-48f6-957d-ea00c5a0d3f9")
                        },
                        new
                        {
                            Id = 4,
                            BlockNumber = 17,
                            ColorId = 1,
                            CreatedAt = new DateTime(2025, 7, 6, 7, 10, 41, 273, DateTimeKind.Utc).AddTicks(9266),
                            IsDeleted = false,
                            PieceNumber = 967,
                            Price = 6.24f,
                            ProductModelId = 2,
                            Size = "160",
                            Stock = 77,
                            Thumbnail = "https://loremflickr.com/320/240?lock=2039359951",
                            UpdatedAt = new DateTime(2025, 7, 6, 7, 10, 41, 273, DateTimeKind.Utc).AddTicks(9266),
                            UserId = new Guid("3ca4ae80-3af8-48f6-957d-ea00c5a0d3f9")
                        },
                        new
                        {
                            Id = 5,
                            BlockNumber = 14,
                            ColorId = 2,
                            CreatedAt = new DateTime(2025, 7, 6, 7, 10, 41, 273, DateTimeKind.Utc).AddTicks(9300),
                            IsDeleted = false,
                            PieceNumber = 559,
                            Price = 7.53f,
                            ProductModelId = 1,
                            Size = "96",
                            Stock = 28,
                            Thumbnail = "https://loremflickr.com/320/240?lock=1990136250",
                            UpdatedAt = new DateTime(2025, 7, 6, 7, 10, 41, 273, DateTimeKind.Utc).AddTicks(9300),
                            UserId = new Guid("3ca4ae80-3af8-48f6-957d-ea00c5a0d3f9")
                        },
                        new
                        {
                            Id = 6,
                            BlockNumber = 14,
                            ColorId = 1,
                            CreatedAt = new DateTime(2025, 7, 6, 7, 10, 41, 273, DateTimeKind.Utc).AddTicks(9330),
                            IsDeleted = false,
                            PieceNumber = 740,
                            Price = 3.32f,
                            ProductModelId = 2,
                            Size = "192",
                            Stock = 97,
                            Thumbnail = "https://loremflickr.com/320/240?lock=1801630161",
                            UpdatedAt = new DateTime(2025, 7, 6, 7, 10, 41, 273, DateTimeKind.Utc).AddTicks(9330),
                            UserId = new Guid("3ca4ae80-3af8-48f6-957d-ea00c5a0d3f9")
                        },
                        new
                        {
                            Id = 7,
                            BlockNumber = 19,
                            ColorId = 3,
                            CreatedAt = new DateTime(2025, 7, 6, 7, 10, 41, 273, DateTimeKind.Utc).AddTicks(9369),
                            IsDeleted = false,
                            PieceNumber = 624,
                            Price = 0.92f,
                            ProductModelId = 2,
                            Size = "192",
                            Stock = 66,
                            Thumbnail = "https://loremflickr.com/320/240?lock=924510234",
                            UpdatedAt = new DateTime(2025, 7, 6, 7, 10, 41, 273, DateTimeKind.Utc).AddTicks(9368),
                            UserId = new Guid("3ca4ae80-3af8-48f6-957d-ea00c5a0d3f9")
                        },
                        new
                        {
                            Id = 8,
                            BlockNumber = 7,
                            ColorId = 2,
                            CreatedAt = new DateTime(2025, 7, 6, 7, 10, 41, 273, DateTimeKind.Utc).AddTicks(9398),
                            IsDeleted = false,
                            PieceNumber = 701,
                            Price = 13.61f,
                            ProductModelId = 1,
                            Size = "160",
                            Stock = 9,
                            Thumbnail = "https://loremflickr.com/320/240?lock=67296554",
                            UpdatedAt = new DateTime(2025, 7, 6, 7, 10, 41, 273, DateTimeKind.Utc).AddTicks(9398),
                            UserId = new Guid("3ca4ae80-3af8-48f6-957d-ea00c5a0d3f9")
                        },
                        new
                        {
                            Id = 9,
                            BlockNumber = 13,
                            ColorId = 2,
                            CreatedAt = new DateTime(2025, 7, 6, 7, 10, 41, 273, DateTimeKind.Utc).AddTicks(9430),
                            IsDeleted = false,
                            PieceNumber = 540,
                            Price = 14.56f,
                            ProductModelId = 1,
                            Size = "96",
                            Stock = 70,
                            Thumbnail = "https://loremflickr.com/320/240?lock=1648169281",
                            UpdatedAt = new DateTime(2025, 7, 6, 7, 10, 41, 273, DateTimeKind.Utc).AddTicks(9430),
                            UserId = new Guid("3ca4ae80-3af8-48f6-957d-ea00c5a0d3f9")
                        },
                        new
                        {
                            Id = 10,
                            BlockNumber = 18,
                            ColorId = 1,
                            CreatedAt = new DateTime(2025, 7, 6, 7, 10, 41, 273, DateTimeKind.Utc).AddTicks(9462),
                            IsDeleted = false,
                            PieceNumber = 297,
                            Price = 8.89f,
                            ProductModelId = 1,
                            Size = "160",
                            Stock = 48,
                            Thumbnail = "https://loremflickr.com/320/240?lock=1186008105",
                            UpdatedAt = new DateTime(2025, 7, 6, 7, 10, 41, 273, DateTimeKind.Utc).AddTicks(9461),
                            UserId = new Guid("3ca4ae80-3af8-48f6-957d-ea00c5a0d3f9")
                        },
                        new
                        {
                            Id = 11,
                            BlockNumber = 14,
                            ColorId = 2,
                            CreatedAt = new DateTime(2025, 7, 6, 7, 10, 41, 273, DateTimeKind.Utc).AddTicks(9516),
                            IsDeleted = false,
                            PieceNumber = 457,
                            Price = 6.11f,
                            ProductModelId = 1,
                            Size = "192",
                            Stock = 29,
                            Thumbnail = "https://loremflickr.com/320/240?lock=2134482409",
                            UpdatedAt = new DateTime(2025, 7, 6, 7, 10, 41, 273, DateTimeKind.Utc).AddTicks(9515),
                            UserId = new Guid("3ca4ae80-3af8-48f6-957d-ea00c5a0d3f9")
                        },
                        new
                        {
                            Id = 12,
                            BlockNumber = 10,
                            ColorId = 1,
                            CreatedAt = new DateTime(2025, 7, 6, 7, 10, 41, 273, DateTimeKind.Utc).AddTicks(9549),
                            IsDeleted = false,
                            PieceNumber = 787,
                            Price = 2.3f,
                            ProductModelId = 1,
                            Size = "160",
                            Stock = 89,
                            Thumbnail = "https://loremflickr.com/320/240?lock=1040026534",
                            UpdatedAt = new DateTime(2025, 7, 6, 7, 10, 41, 273, DateTimeKind.Utc).AddTicks(9549),
                            UserId = new Guid("3ca4ae80-3af8-48f6-957d-ea00c5a0d3f9")
                        },
                        new
                        {
                            Id = 13,
                            BlockNumber = 6,
                            ColorId = 3,
                            CreatedAt = new DateTime(2025, 7, 6, 7, 10, 41, 273, DateTimeKind.Utc).AddTicks(9581),
                            IsDeleted = false,
                            PieceNumber = 916,
                            Price = 7.53f,
                            ProductModelId = 2,
                            Size = "160",
                            Stock = 1,
                            Thumbnail = "https://loremflickr.com/320/240?lock=1149504627",
                            UpdatedAt = new DateTime(2025, 7, 6, 7, 10, 41, 273, DateTimeKind.Utc).AddTicks(9580),
                            UserId = new Guid("3ca4ae80-3af8-48f6-957d-ea00c5a0d3f9")
                        },
                        new
                        {
                            Id = 14,
                            BlockNumber = 4,
                            ColorId = 3,
                            CreatedAt = new DateTime(2025, 7, 6, 7, 10, 41, 273, DateTimeKind.Utc).AddTicks(9630),
                            IsDeleted = false,
                            PieceNumber = 223,
                            Price = 12.28f,
                            ProductModelId = 2,
                            Size = "160",
                            Stock = 25,
                            Thumbnail = "https://loremflickr.com/320/240?lock=910550729",
                            UpdatedAt = new DateTime(2025, 7, 6, 7, 10, 41, 273, DateTimeKind.Utc).AddTicks(9630),
                            UserId = new Guid("3ca4ae80-3af8-48f6-957d-ea00c5a0d3f9")
                        },
                        new
                        {
                            Id = 15,
                            BlockNumber = 14,
                            ColorId = 1,
                            CreatedAt = new DateTime(2025, 7, 6, 7, 10, 41, 273, DateTimeKind.Utc).AddTicks(9672),
                            IsDeleted = false,
                            PieceNumber = 137,
                            Price = 13.87f,
                            ProductModelId = 2,
                            Size = "128",
                            Stock = 75,
                            Thumbnail = "https://loremflickr.com/320/240?lock=523651742",
                            UpdatedAt = new DateTime(2025, 7, 6, 7, 10, 41, 273, DateTimeKind.Utc).AddTicks(9662),
                            UserId = new Guid("3ca4ae80-3af8-48f6-957d-ea00c5a0d3f9")
                        },
                        new
                        {
                            Id = 16,
                            BlockNumber = 20,
                            ColorId = 1,
                            CreatedAt = new DateTime(2025, 7, 6, 7, 10, 41, 273, DateTimeKind.Utc).AddTicks(9706),
                            IsDeleted = false,
                            PieceNumber = 237,
                            Price = 9.58f,
                            ProductModelId = 2,
                            Size = "192",
                            Stock = 89,
                            Thumbnail = "https://loremflickr.com/320/240?lock=1648401953",
                            UpdatedAt = new DateTime(2025, 7, 6, 7, 10, 41, 273, DateTimeKind.Utc).AddTicks(9706),
                            UserId = new Guid("3ca4ae80-3af8-48f6-957d-ea00c5a0d3f9")
                        },
                        new
                        {
                            Id = 17,
                            BlockNumber = 17,
                            ColorId = 1,
                            CreatedAt = new DateTime(2025, 7, 6, 7, 10, 41, 273, DateTimeKind.Utc).AddTicks(9739),
                            IsDeleted = false,
                            PieceNumber = 824,
                            Price = 0.57f,
                            ProductModelId = 1,
                            Size = "160",
                            Stock = 64,
                            Thumbnail = "https://loremflickr.com/320/240?lock=607077782",
                            UpdatedAt = new DateTime(2025, 7, 6, 7, 10, 41, 273, DateTimeKind.Utc).AddTicks(9738),
                            UserId = new Guid("3ca4ae80-3af8-48f6-957d-ea00c5a0d3f9")
                        },
                        new
                        {
                            Id = 18,
                            BlockNumber = 15,
                            ColorId = 3,
                            CreatedAt = new DateTime(2025, 7, 6, 7, 10, 41, 273, DateTimeKind.Utc).AddTicks(9767),
                            IsDeleted = false,
                            PieceNumber = 460,
                            Price = 5.79f,
                            ProductModelId = 2,
                            Size = "192",
                            Stock = 24,
                            Thumbnail = "https://loremflickr.com/320/240?lock=165418203",
                            UpdatedAt = new DateTime(2025, 7, 6, 7, 10, 41, 273, DateTimeKind.Utc).AddTicks(9767),
                            UserId = new Guid("3ca4ae80-3af8-48f6-957d-ea00c5a0d3f9")
                        },
                        new
                        {
                            Id = 19,
                            BlockNumber = 1,
                            ColorId = 3,
                            CreatedAt = new DateTime(2025, 7, 6, 7, 10, 41, 273, DateTimeKind.Utc).AddTicks(9801),
                            IsDeleted = false,
                            PieceNumber = 344,
                            Price = 4.84f,
                            ProductModelId = 2,
                            Size = "96",
                            Stock = 98,
                            Thumbnail = "https://loremflickr.com/320/240?lock=1313231424",
                            UpdatedAt = new DateTime(2025, 7, 6, 7, 10, 41, 273, DateTimeKind.Utc).AddTicks(9801),
                            UserId = new Guid("3ca4ae80-3af8-48f6-957d-ea00c5a0d3f9")
                        },
                        new
                        {
                            Id = 20,
                            BlockNumber = 19,
                            ColorId = 2,
                            CreatedAt = new DateTime(2025, 7, 6, 7, 10, 41, 273, DateTimeKind.Utc).AddTicks(9837),
                            IsDeleted = false,
                            PieceNumber = 529,
                            Price = 1.68f,
                            ProductModelId = 1,
                            Size = "160",
                            Stock = 82,
                            Thumbnail = "https://loremflickr.com/320/240?lock=625375352",
                            UpdatedAt = new DateTime(2025, 7, 6, 7, 10, 41, 273, DateTimeKind.Utc).AddTicks(9837),
                            UserId = new Guid("3ca4ae80-3af8-48f6-957d-ea00c5a0d3f9")
                        },
                        new
                        {
                            Id = 21,
                            BlockNumber = 4,
                            ColorId = 3,
                            CreatedAt = new DateTime(2025, 7, 6, 7, 10, 41, 273, DateTimeKind.Utc).AddTicks(9883),
                            IsDeleted = false,
                            PieceNumber = 813,
                            Price = 10.58f,
                            ProductModelId = 2,
                            Size = "192",
                            Stock = 10,
                            Thumbnail = "https://loremflickr.com/320/240?lock=325125655",
                            UpdatedAt = new DateTime(2025, 7, 6, 7, 10, 41, 273, DateTimeKind.Utc).AddTicks(9883),
                            UserId = new Guid("3ca4ae80-3af8-48f6-957d-ea00c5a0d3f9")
                        },
                        new
                        {
                            Id = 22,
                            BlockNumber = 14,
                            ColorId = 3,
                            CreatedAt = new DateTime(2025, 7, 6, 7, 10, 41, 273, DateTimeKind.Utc).AddTicks(9919),
                            IsDeleted = false,
                            PieceNumber = 161,
                            Price = 13f,
                            ProductModelId = 1,
                            Size = "128",
                            Stock = 37,
                            Thumbnail = "https://loremflickr.com/320/240?lock=1777590470",
                            UpdatedAt = new DateTime(2025, 7, 6, 7, 10, 41, 273, DateTimeKind.Utc).AddTicks(9919),
                            UserId = new Guid("3ca4ae80-3af8-48f6-957d-ea00c5a0d3f9")
                        },
                        new
                        {
                            Id = 23,
                            BlockNumber = 9,
                            ColorId = 3,
                            CreatedAt = new DateTime(2025, 7, 6, 7, 10, 41, 273, DateTimeKind.Utc).AddTicks(9956),
                            IsDeleted = false,
                            PieceNumber = 138,
                            Price = 7.13f,
                            ProductModelId = 1,
                            Size = "96",
                            Stock = 97,
                            Thumbnail = "https://loremflickr.com/320/240?lock=344428136",
                            UpdatedAt = new DateTime(2025, 7, 6, 7, 10, 41, 273, DateTimeKind.Utc).AddTicks(9956),
                            UserId = new Guid("3ca4ae80-3af8-48f6-957d-ea00c5a0d3f9")
                        },
                        new
                        {
                            Id = 24,
                            BlockNumber = 12,
                            ColorId = 1,
                            CreatedAt = new DateTime(2025, 7, 6, 7, 10, 41, 273, DateTimeKind.Utc).AddTicks(9987),
                            IsDeleted = false,
                            PieceNumber = 674,
                            Price = 2.64f,
                            ProductModelId = 1,
                            Size = "96",
                            Stock = 19,
                            Thumbnail = "https://loremflickr.com/320/240?lock=1357523284",
                            UpdatedAt = new DateTime(2025, 7, 6, 7, 10, 41, 273, DateTimeKind.Utc).AddTicks(9987),
                            UserId = new Guid("3ca4ae80-3af8-48f6-957d-ea00c5a0d3f9")
                        },
                        new
                        {
                            Id = 25,
                            BlockNumber = 15,
                            ColorId = 2,
                            CreatedAt = new DateTime(2025, 7, 6, 7, 10, 41, 274, DateTimeKind.Utc).AddTicks(9),
                            IsDeleted = false,
                            PieceNumber = 679,
                            Price = 9.44f,
                            ProductModelId = 2,
                            Size = "192",
                            Stock = 30,
                            Thumbnail = "https://loremflickr.com/320/240?lock=1165712871",
                            UpdatedAt = new DateTime(2025, 7, 6, 7, 10, 41, 274, DateTimeKind.Utc).AddTicks(9),
                            UserId = new Guid("3ca4ae80-3af8-48f6-957d-ea00c5a0d3f9")
                        },
                        new
                        {
                            Id = 26,
                            BlockNumber = 9,
                            ColorId = 3,
                            CreatedAt = new DateTime(2025, 7, 6, 7, 10, 41, 274, DateTimeKind.Utc).AddTicks(25),
                            IsDeleted = false,
                            PieceNumber = 903,
                            Price = 7.72f,
                            ProductModelId = 2,
                            Size = "192",
                            Stock = 92,
                            Thumbnail = "https://loremflickr.com/320/240?lock=1290560587",
                            UpdatedAt = new DateTime(2025, 7, 6, 7, 10, 41, 274, DateTimeKind.Utc).AddTicks(25),
                            UserId = new Guid("3ca4ae80-3af8-48f6-957d-ea00c5a0d3f9")
                        },
                        new
                        {
                            Id = 27,
                            BlockNumber = 11,
                            ColorId = 2,
                            CreatedAt = new DateTime(2025, 7, 6, 7, 10, 41, 274, DateTimeKind.Utc).AddTicks(46),
                            IsDeleted = false,
                            PieceNumber = 506,
                            Price = 1.37f,
                            ProductModelId = 2,
                            Size = "160",
                            Stock = 40,
                            Thumbnail = "https://loremflickr.com/320/240?lock=735917076",
                            UpdatedAt = new DateTime(2025, 7, 6, 7, 10, 41, 274, DateTimeKind.Utc).AddTicks(46),
                            UserId = new Guid("3ca4ae80-3af8-48f6-957d-ea00c5a0d3f9")
                        },
                        new
                        {
                            Id = 28,
                            BlockNumber = 7,
                            ColorId = 1,
                            CreatedAt = new DateTime(2025, 7, 6, 7, 10, 41, 274, DateTimeKind.Utc).AddTicks(70),
                            IsDeleted = false,
                            PieceNumber = 291,
                            Price = 9.52f,
                            ProductModelId = 1,
                            Size = "160",
                            Stock = 45,
                            Thumbnail = "https://loremflickr.com/320/240?lock=1437790182",
                            UpdatedAt = new DateTime(2025, 7, 6, 7, 10, 41, 274, DateTimeKind.Utc).AddTicks(69),
                            UserId = new Guid("3ca4ae80-3af8-48f6-957d-ea00c5a0d3f9")
                        },
                        new
                        {
                            Id = 29,
                            BlockNumber = 6,
                            ColorId = 3,
                            CreatedAt = new DateTime(2025, 7, 6, 7, 10, 41, 274, DateTimeKind.Utc).AddTicks(95),
                            IsDeleted = false,
                            PieceNumber = 466,
                            Price = 6.58f,
                            ProductModelId = 1,
                            Size = "128",
                            Stock = 68,
                            Thumbnail = "https://loremflickr.com/320/240?lock=1217949379",
                            UpdatedAt = new DateTime(2025, 7, 6, 7, 10, 41, 274, DateTimeKind.Utc).AddTicks(94),
                            UserId = new Guid("3ca4ae80-3af8-48f6-957d-ea00c5a0d3f9")
                        },
                        new
                        {
                            Id = 30,
                            BlockNumber = 3,
                            ColorId = 2,
                            CreatedAt = new DateTime(2025, 7, 6, 7, 10, 41, 274, DateTimeKind.Utc).AddTicks(133),
                            IsDeleted = false,
                            PieceNumber = 449,
                            Price = 12.83f,
                            ProductModelId = 1,
                            Size = "96",
                            Stock = 84,
                            Thumbnail = "https://loremflickr.com/320/240?lock=2066781791",
                            UpdatedAt = new DateTime(2025, 7, 6, 7, 10, 41, 274, DateTimeKind.Utc).AddTicks(132),
                            UserId = new Guid("3ca4ae80-3af8-48f6-957d-ea00c5a0d3f9")
                        },
                        new
                        {
                            Id = 31,
                            BlockNumber = 8,
                            ColorId = 1,
                            CreatedAt = new DateTime(2025, 7, 6, 7, 10, 41, 274, DateTimeKind.Utc).AddTicks(171),
                            IsDeleted = false,
                            PieceNumber = 167,
                            Price = 8.7f,
                            ProductModelId = 2,
                            Size = "96",
                            Stock = 10,
                            Thumbnail = "https://loremflickr.com/320/240?lock=1501223953",
                            UpdatedAt = new DateTime(2025, 7, 6, 7, 10, 41, 274, DateTimeKind.Utc).AddTicks(171),
                            UserId = new Guid("3ca4ae80-3af8-48f6-957d-ea00c5a0d3f9")
                        },
                        new
                        {
                            Id = 32,
                            BlockNumber = 6,
                            ColorId = 3,
                            CreatedAt = new DateTime(2025, 7, 6, 7, 10, 41, 274, DateTimeKind.Utc).AddTicks(190),
                            IsDeleted = false,
                            PieceNumber = 482,
                            Price = 8.13f,
                            ProductModelId = 2,
                            Size = "128",
                            Stock = 0,
                            Thumbnail = "https://loremflickr.com/320/240?lock=1543154439",
                            UpdatedAt = new DateTime(2025, 7, 6, 7, 10, 41, 274, DateTimeKind.Utc).AddTicks(190),
                            UserId = new Guid("3ca4ae80-3af8-48f6-957d-ea00c5a0d3f9")
                        },
                        new
                        {
                            Id = 33,
                            BlockNumber = 11,
                            ColorId = 2,
                            CreatedAt = new DateTime(2025, 7, 6, 7, 10, 41, 274, DateTimeKind.Utc).AddTicks(207),
                            IsDeleted = false,
                            PieceNumber = 980,
                            Price = 2.83f,
                            ProductModelId = 2,
                            Size = "128",
                            Stock = 52,
                            Thumbnail = "https://loremflickr.com/320/240?lock=1075438473",
                            UpdatedAt = new DateTime(2025, 7, 6, 7, 10, 41, 274, DateTimeKind.Utc).AddTicks(207),
                            UserId = new Guid("3ca4ae80-3af8-48f6-957d-ea00c5a0d3f9")
                        },
                        new
                        {
                            Id = 34,
                            BlockNumber = 20,
                            ColorId = 1,
                            CreatedAt = new DateTime(2025, 7, 6, 7, 10, 41, 274, DateTimeKind.Utc).AddTicks(223),
                            IsDeleted = false,
                            PieceNumber = 956,
                            Price = 0.74f,
                            ProductModelId = 1,
                            Size = "96",
                            Stock = 32,
                            Thumbnail = "https://loremflickr.com/320/240?lock=618542645",
                            UpdatedAt = new DateTime(2025, 7, 6, 7, 10, 41, 274, DateTimeKind.Utc).AddTicks(223),
                            UserId = new Guid("3ca4ae80-3af8-48f6-957d-ea00c5a0d3f9")
                        },
                        new
                        {
                            Id = 35,
                            BlockNumber = 6,
                            ColorId = 2,
                            CreatedAt = new DateTime(2025, 7, 6, 7, 10, 41, 274, DateTimeKind.Utc).AddTicks(239),
                            IsDeleted = false,
                            PieceNumber = 677,
                            Price = 14.29f,
                            ProductModelId = 1,
                            Size = "96",
                            Stock = 86,
                            Thumbnail = "https://loremflickr.com/320/240?lock=1240531553",
                            UpdatedAt = new DateTime(2025, 7, 6, 7, 10, 41, 274, DateTimeKind.Utc).AddTicks(239),
                            UserId = new Guid("3ca4ae80-3af8-48f6-957d-ea00c5a0d3f9")
                        },
                        new
                        {
                            Id = 36,
                            BlockNumber = 6,
                            ColorId = 1,
                            CreatedAt = new DateTime(2025, 7, 6, 7, 10, 41, 274, DateTimeKind.Utc).AddTicks(255),
                            IsDeleted = false,
                            PieceNumber = 378,
                            Price = 4.31f,
                            ProductModelId = 2,
                            Size = "96",
                            Stock = 0,
                            Thumbnail = "https://loremflickr.com/320/240?lock=615841914",
                            UpdatedAt = new DateTime(2025, 7, 6, 7, 10, 41, 274, DateTimeKind.Utc).AddTicks(255),
                            UserId = new Guid("3ca4ae80-3af8-48f6-957d-ea00c5a0d3f9")
                        },
                        new
                        {
                            Id = 37,
                            BlockNumber = 9,
                            ColorId = 1,
                            CreatedAt = new DateTime(2025, 7, 6, 7, 10, 41, 274, DateTimeKind.Utc).AddTicks(286),
                            IsDeleted = false,
                            PieceNumber = 325,
                            Price = 4.33f,
                            ProductModelId = 1,
                            Size = "192",
                            Stock = 79,
                            Thumbnail = "https://loremflickr.com/320/240?lock=931884593",
                            UpdatedAt = new DateTime(2025, 7, 6, 7, 10, 41, 274, DateTimeKind.Utc).AddTicks(286),
                            UserId = new Guid("3ca4ae80-3af8-48f6-957d-ea00c5a0d3f9")
                        },
                        new
                        {
                            Id = 38,
                            BlockNumber = 1,
                            ColorId = 1,
                            CreatedAt = new DateTime(2025, 7, 6, 7, 10, 41, 274, DateTimeKind.Utc).AddTicks(314),
                            IsDeleted = false,
                            PieceNumber = 316,
                            Price = 13.59f,
                            ProductModelId = 2,
                            Size = "160",
                            Stock = 59,
                            Thumbnail = "https://loremflickr.com/320/240?lock=938685531",
                            UpdatedAt = new DateTime(2025, 7, 6, 7, 10, 41, 274, DateTimeKind.Utc).AddTicks(314),
                            UserId = new Guid("3ca4ae80-3af8-48f6-957d-ea00c5a0d3f9")
                        },
                        new
                        {
                            Id = 39,
                            BlockNumber = 3,
                            ColorId = 2,
                            CreatedAt = new DateTime(2025, 7, 6, 7, 10, 41, 274, DateTimeKind.Utc).AddTicks(354),
                            IsDeleted = false,
                            PieceNumber = 356,
                            Price = 10.92f,
                            ProductModelId = 1,
                            Size = "96",
                            Stock = 49,
                            Thumbnail = "https://loremflickr.com/320/240?lock=61750871",
                            UpdatedAt = new DateTime(2025, 7, 6, 7, 10, 41, 274, DateTimeKind.Utc).AddTicks(354),
                            UserId = new Guid("3ca4ae80-3af8-48f6-957d-ea00c5a0d3f9")
                        },
                        new
                        {
                            Id = 40,
                            BlockNumber = 11,
                            ColorId = 3,
                            CreatedAt = new DateTime(2025, 7, 6, 7, 10, 41, 274, DateTimeKind.Utc).AddTicks(385),
                            IsDeleted = false,
                            PieceNumber = 776,
                            Price = 6.56f,
                            ProductModelId = 1,
                            Size = "192",
                            Stock = 66,
                            Thumbnail = "https://loremflickr.com/320/240?lock=2097224650",
                            UpdatedAt = new DateTime(2025, 7, 6, 7, 10, 41, 274, DateTimeKind.Utc).AddTicks(385),
                            UserId = new Guid("3ca4ae80-3af8-48f6-957d-ea00c5a0d3f9")
                        },
                        new
                        {
                            Id = 41,
                            BlockNumber = 4,
                            ColorId = 1,
                            CreatedAt = new DateTime(2025, 7, 6, 7, 10, 41, 274, DateTimeKind.Utc).AddTicks(416),
                            IsDeleted = false,
                            PieceNumber = 797,
                            Price = 10.21f,
                            ProductModelId = 1,
                            Size = "160",
                            Stock = 8,
                            Thumbnail = "https://loremflickr.com/320/240?lock=90023824",
                            UpdatedAt = new DateTime(2025, 7, 6, 7, 10, 41, 274, DateTimeKind.Utc).AddTicks(416),
                            UserId = new Guid("3ca4ae80-3af8-48f6-957d-ea00c5a0d3f9")
                        },
                        new
                        {
                            Id = 42,
                            BlockNumber = 4,
                            ColorId = 2,
                            CreatedAt = new DateTime(2025, 7, 6, 7, 10, 41, 274, DateTimeKind.Utc).AddTicks(449),
                            IsDeleted = false,
                            PieceNumber = 65,
                            Price = 6.5f,
                            ProductModelId = 1,
                            Size = "128",
                            Stock = 39,
                            Thumbnail = "https://loremflickr.com/320/240?lock=269080341",
                            UpdatedAt = new DateTime(2025, 7, 6, 7, 10, 41, 274, DateTimeKind.Utc).AddTicks(448),
                            UserId = new Guid("3ca4ae80-3af8-48f6-957d-ea00c5a0d3f9")
                        },
                        new
                        {
                            Id = 43,
                            BlockNumber = 15,
                            ColorId = 2,
                            CreatedAt = new DateTime(2025, 7, 6, 7, 10, 41, 274, DateTimeKind.Utc).AddTicks(479),
                            IsDeleted = false,
                            PieceNumber = 39,
                            Price = 5.2f,
                            ProductModelId = 2,
                            Size = "128",
                            Stock = 63,
                            Thumbnail = "https://loremflickr.com/320/240?lock=1599636314",
                            UpdatedAt = new DateTime(2025, 7, 6, 7, 10, 41, 274, DateTimeKind.Utc).AddTicks(478),
                            UserId = new Guid("3ca4ae80-3af8-48f6-957d-ea00c5a0d3f9")
                        },
                        new
                        {
                            Id = 44,
                            BlockNumber = 16,
                            ColorId = 1,
                            CreatedAt = new DateTime(2025, 7, 6, 7, 10, 41, 274, DateTimeKind.Utc).AddTicks(509),
                            IsDeleted = false,
                            PieceNumber = 173,
                            Price = 13.97f,
                            ProductModelId = 1,
                            Size = "128",
                            Stock = 19,
                            Thumbnail = "https://loremflickr.com/320/240?lock=140079380",
                            UpdatedAt = new DateTime(2025, 7, 6, 7, 10, 41, 274, DateTimeKind.Utc).AddTicks(509),
                            UserId = new Guid("3ca4ae80-3af8-48f6-957d-ea00c5a0d3f9")
                        },
                        new
                        {
                            Id = 45,
                            BlockNumber = 7,
                            ColorId = 3,
                            CreatedAt = new DateTime(2025, 7, 6, 7, 10, 41, 274, DateTimeKind.Utc).AddTicks(540),
                            IsDeleted = false,
                            PieceNumber = 393,
                            Price = 12.2f,
                            ProductModelId = 1,
                            Size = "192",
                            Stock = 8,
                            Thumbnail = "https://loremflickr.com/320/240?lock=1214344495",
                            UpdatedAt = new DateTime(2025, 7, 6, 7, 10, 41, 274, DateTimeKind.Utc).AddTicks(539),
                            UserId = new Guid("3ca4ae80-3af8-48f6-957d-ea00c5a0d3f9")
                        },
                        new
                        {
                            Id = 46,
                            BlockNumber = 4,
                            ColorId = 3,
                            CreatedAt = new DateTime(2025, 7, 6, 7, 10, 41, 274, DateTimeKind.Utc).AddTicks(569),
                            IsDeleted = false,
                            PieceNumber = 521,
                            Price = 12.94f,
                            ProductModelId = 1,
                            Size = "96",
                            Stock = 97,
                            Thumbnail = "https://loremflickr.com/320/240?lock=1935132270",
                            UpdatedAt = new DateTime(2025, 7, 6, 7, 10, 41, 274, DateTimeKind.Utc).AddTicks(569),
                            UserId = new Guid("3ca4ae80-3af8-48f6-957d-ea00c5a0d3f9")
                        },
                        new
                        {
                            Id = 47,
                            BlockNumber = 15,
                            ColorId = 3,
                            CreatedAt = new DateTime(2025, 7, 6, 7, 10, 41, 274, DateTimeKind.Utc).AddTicks(600),
                            IsDeleted = false,
                            PieceNumber = 787,
                            Price = 0.37f,
                            ProductModelId = 2,
                            Size = "192",
                            Stock = 54,
                            Thumbnail = "https://loremflickr.com/320/240?lock=1940371115",
                            UpdatedAt = new DateTime(2025, 7, 6, 7, 10, 41, 274, DateTimeKind.Utc).AddTicks(600),
                            UserId = new Guid("3ca4ae80-3af8-48f6-957d-ea00c5a0d3f9")
                        },
                        new
                        {
                            Id = 48,
                            BlockNumber = 14,
                            ColorId = 3,
                            CreatedAt = new DateTime(2025, 7, 6, 7, 10, 41, 274, DateTimeKind.Utc).AddTicks(633),
                            IsDeleted = false,
                            PieceNumber = 521,
                            Price = 7.08f,
                            ProductModelId = 2,
                            Size = "160",
                            Stock = 67,
                            Thumbnail = "https://loremflickr.com/320/240?lock=408621399",
                            UpdatedAt = new DateTime(2025, 7, 6, 7, 10, 41, 274, DateTimeKind.Utc).AddTicks(633),
                            UserId = new Guid("3ca4ae80-3af8-48f6-957d-ea00c5a0d3f9")
                        },
                        new
                        {
                            Id = 49,
                            BlockNumber = 11,
                            ColorId = 3,
                            CreatedAt = new DateTime(2025, 7, 6, 7, 10, 41, 274, DateTimeKind.Utc).AddTicks(676),
                            IsDeleted = false,
                            PieceNumber = 84,
                            Price = 10.49f,
                            ProductModelId = 1,
                            Size = "192",
                            Stock = 79,
                            Thumbnail = "https://loremflickr.com/320/240?lock=494383077",
                            UpdatedAt = new DateTime(2025, 7, 6, 7, 10, 41, 274, DateTimeKind.Utc).AddTicks(675),
                            UserId = new Guid("3ca4ae80-3af8-48f6-957d-ea00c5a0d3f9")
                        },
                        new
                        {
                            Id = 50,
                            BlockNumber = 4,
                            ColorId = 2,
                            CreatedAt = new DateTime(2025, 7, 6, 7, 10, 41, 274, DateTimeKind.Utc).AddTicks(706),
                            IsDeleted = false,
                            PieceNumber = 78,
                            Price = 10.21f,
                            ProductModelId = 1,
                            Size = "192",
                            Stock = 45,
                            Thumbnail = "https://loremflickr.com/320/240?lock=77821343",
                            UpdatedAt = new DateTime(2025, 7, 6, 7, 10, 41, 274, DateTimeKind.Utc).AddTicks(706),
                            UserId = new Guid("3ca4ae80-3af8-48f6-957d-ea00c5a0d3f9")
                        });
                });

            modelBuilder.Entity("Warehouse.Api.src.Domain.Entities.ProductColor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("color_name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("product_colors", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 7, 6, 7, 10, 40, 966, DateTimeKind.Utc).AddTicks(9769),
                            IsDeleted = false,
                            Name = "BK"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 7, 6, 7, 10, 40, 966, DateTimeKind.Utc).AddTicks(9938),
                            IsDeleted = false,
                            Name = "Golden"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 7, 6, 7, 10, 40, 966, DateTimeKind.Utc).AddTicks(9939),
                            IsDeleted = false,
                            Name = "White"
                        });
                });

            modelBuilder.Entity("Warehouse.Api.src.Domain.Entities.ProductModelName", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model_name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("product_model_names", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 7, 6, 7, 10, 40, 972, DateTimeKind.Utc).AddTicks(4093),
                            IsDeleted = false,
                            Name = "1296"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 7, 6, 7, 10, 40, 972, DateTimeKind.Utc).AddTicks(4095),
                            IsDeleted = false,
                            Name = "5575"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 7, 6, 7, 10, 40, 972, DateTimeKind.Utc).AddTicks(4097),
                            IsDeleted = false,
                            Name = "5175"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 7, 6, 7, 10, 40, 972, DateTimeKind.Utc).AddTicks(4098),
                            IsDeleted = false,
                            Name = "708"
                        });
                });

            modelBuilder.Entity("Warehouse.Api.src.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("fullname");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("password");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("3ca4ae80-3af8-48f6-957d-ea00c5a0d3f9"),
                            CreatedAt = new DateTime(2025, 7, 6, 7, 10, 40, 979, DateTimeKind.Utc).AddTicks(5688),
                            Email = "admin@gmail.com",
                            Fullname = "Admin",
                            IsDeleted = false,
                            Password = "$2a$11$J8d3qU8KaUMIj2Tk/X89U.23kIBj5ZaidLQd1pqOiq1bQ2CUsw43W"
                        });
                });

            modelBuilder.Entity("Warehouse.Api.src.Domain.Entities.Order", b =>
                {
                    b.HasOne("Warehouse.Api.src.Domain.Entities.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_orders_customers_user_id");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Warehouse.Api.src.Domain.Entities.Product", b =>
                {
                    b.HasOne("Warehouse.Api.src.Domain.Entities.ProductColor", "ProductColor")
                        .WithMany("Products")
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_products_product_colors_product_color_id");

                    b.HasOne("Warehouse.Api.src.Domain.Entities.ProductModelName", "ProductModelName")
                        .WithMany("Products")
                        .HasForeignKey("ProductModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_products_product_models_names_product_model_id");

                    b.HasOne("Warehouse.Api.src.Domain.Entities.User", "User")
                        .WithMany("Products")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_products_users_user_id");

                    b.Navigation("ProductColor");

                    b.Navigation("ProductModelName");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Warehouse.Api.src.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Warehouse.Api.src.Domain.Entities.ProductColor", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Warehouse.Api.src.Domain.Entities.ProductModelName", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Warehouse.Api.src.Domain.Entities.User", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
